version: '2.2'

services:

  r4: # ------------------------------------------------------------------------
    image: smartonfhir/hapi-5:r4-synthea
    environment:
      PORT: 42112
      HOST: 127.0.0.1
    ports:
      - 127.0.0.1:42112:8080
    command: ["sh", "-c", "
      envsubst < /tmp/hapi.properties.tpl > /config/hapi.properties &&
      envsubst < /tmp/server.xml > /usr/local/tomcat/conf/server.xml &&
      catalina.sh run"]
